name: Build Zygisk-Il2CppDumper

on:
  workflow_dispatch:  # 手動觸發
    inputs:
      package_name:
        description: 'Game package name (e.g., com.dkgame.gplay.crisisactiontw)'
        required: true
        default: 'com.dkgame.gplay.crisisactiontw'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'

      - name: Build module
        run: |
          echo "Building for package: ${{ github.event.inputs.package_name }}"
          sed -i "s/id=.*/id=${{ github.event.inputs.package_name }}/" module/module.prop
          sed -i "s/name=.*/name=Zygisk-Il2CppDumper for ${{ github.event.inputs.package_name }}/" module/module.prop
          zip -r module.zip module

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: module
          path: module.zip
