            - 名称：缓存
  用途：actions/cache@v4.2.3
  和：
    # 要缓存和恢复的文件、目录和通配符模式的列表
    小路：
    # 用于恢复和保存缓存的显式密钥
    钥匙：
    # 一个有序的多行字符串，列出了前缀匹配的键，用于在键未发生缓存命中时恢复过时的缓存。注意，在这种情况下，“cache-hit”将返回 false。
    恢复键：#可选
    # 上传过程中用于分割大文件的块大小，以字节为单位
    上传块大小：#可选
    # 启用时可选布尔值，允许 Windows 运行器保存或恢复可以在其他平台上分别恢复或保存的缓存
    enableCrossOsArchive: # 可选，默认为 false
    # 如果未找到缓存条目，则工作流失败
    fail-on-cache-miss: #可选，默认为false
    # 检查给定输入（key、restore-keys）的缓存条目是否存在，无需下载缓存
    lookup-only: # 可选，默认为 false
    # 即使之前的步骤失败，也要运行后续步骤来保存缓存
    save-always: # 可选，默认为 false

    name: Build Zygisk-Il2CppDumper

on:
  workflow_dispatch:  # 手動觸發
    inputs:
      package_name:
        description: 'Game package name (e.g., com.dkgame.gplay.crisisactiontw)'
        required: true
        default: 'com.dkgame.gplay.crisisactiontw'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          cache: 'maven'  # 緩存 Maven 依賴 (可改 gradle)

      - name: Cache build files
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.m2/repository  # Maven 緩存路徑
            module/  # 模組中間文件
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}  # 依賴文件哈希
          restore-keys: |
            ${{ runner.os }}-build-  # 過期緩存前綴
          fail-on-cache-miss: false
          enableCrossOsArchive: false

      - name: Build module
        run: |
          echo "Building for package: ${{ github.event.inputs.package_name }}"
          sed -i "s/id=.*/id=${{ github.event.inputs.package_name }}/" module/module.prop
          sed -i "s/name=.*/name=Zygisk-Il2CppDumper for ${{ github.event.inputs.package_name }}/" module/module.prop
          zip -r module.zip module

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: module
          path: module.zip
          
